# Generated by Django 4.1.5 on 2023-01-28 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='s_cost',
            new_name='s_cost_per_unit',
        ),
    ]
