# Generated by Django 4.1.5 on 2023-01-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_stock_sq_s_name_alter_sq_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sq',
            old_name='quantity',
            new_name='s_in',
        ),
        migrations.AddField(
            model_name='sq',
            name='s_out',
            field=models.IntegerField(default=0),
        ),
    ]
