# Generated by Django 4.1.5 on 2023-01-28 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_quantity_sq_s_in_sq_s_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='s_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='s_name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
