# Generated by Django 4.1.5 on 2023-01-29 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_stock_s_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='s_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='s_name',
            field=models.CharField(max_length=50),
        ),
    ]
