# Generated by Django 4.1.5 on 2023-01-29 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_stock_s_id_alter_stock_s_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='s_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='s_name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
