# Generated by Django 4.1.5 on 2023-01-29 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_stock_s_id_alter_stock_s_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='s_id',
        ),
    ]
