# Generated by Django 4.1.5 on 2023-01-29 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_stock_s_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sq',
        ),
    ]
