# Generated by Django 4.1.5 on 2023-01-29 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_delete_sq'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='s_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='s_name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='sq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_in', models.IntegerField(default=0)),
                ('s_out', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('s_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.stock')),
            ],
            options={
                'unique_together': {('s_name', 'date')},
            },
        ),
    ]
