# Generated by Django 4.1.5 on 2023-01-28 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_s_cost_stock_s_cost_per_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sq',
            old_name='stock',
            new_name='s_name',
        ),
        migrations.AlterUniqueTogether(
            name='sq',
            unique_together={('s_name', 'date')},
        ),
    ]
